### ISSUE TITLE
LoadError: Could not open library 'libasound'

### ISSUE THREAD

**Issue by Kerrick** [arirusso/micromidi#2]
```
kerrick@dirk-tooth:~  ruby-1.9.3-p327 
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=12.04
DISTRIB_CODENAME=precise
DISTRIB_DESCRIPTION="Ubuntu 12.04.1 LTS"
kerrick@dirk-tooth:~  ruby-1.9.3-p327 
$ uname -m
x86_64
kerrick@dirk-tooth:~  ruby-1.9.3-p327 
$ gem install micromidi
Fetching: midi-message-0.3.2.gem (100%)
Fetching: midi-nibbler-0.1.1.gem (100%)
Fetching: ffi-1.2.0.gem (100%)
Building native extensions.  This could take a while...
Fetching: alsa-rawmidi-0.2.14.gem (100%)
Fetching: ffi-coremidi-0.1.8.gem (100%)
Fetching: midi-jruby-0.0.12.gem (100%)
Fetching: midi-winmm-0.1.10.gem (100%)
Fetching: unimidi-0.3.3.gem (100%)
Fetching: midi-eye-0.2.2.gem (100%)
Fetching: micromidi-0.0.9.gem (100%)
Successfully installed midi-message-0.3.2
Successfully installed midi-nibbler-0.1.1
Successfully installed ffi-1.2.0
Successfully installed alsa-rawmidi-0.2.14
Successfully installed ffi-coremidi-0.1.8
Successfully installed midi-jruby-0.0.12
Successfully installed midi-winmm-0.1.10
Successfully installed unimidi-0.3.3
Successfully installed midi-eye-0.2.2
Successfully installed micromidi-0.0.9
10 gems installed
Installing ri documentation for midi-message-0.3.2...
Installing ri documentation for midi-nibbler-0.1.1...
Installing ri documentation for ffi-1.2.0...
Installing ri documentation for alsa-rawmidi-0.2.14...
Installing ri documentation for ffi-coremidi-0.1.8...
Installing ri documentation for midi-jruby-0.0.12...
Installing ri documentation for midi-winmm-0.1.10...
Installing ri documentation for unimidi-0.3.3...
Installing ri documentation for midi-eye-0.2.2...
Installing ri documentation for micromidi-0.0.9...
Installing RDoc documentation for midi-message-0.3.2...
Installing RDoc documentation for midi-nibbler-0.1.1...
Installing RDoc documentation for ffi-1.2.0...
Installing RDoc documentation for alsa-rawmidi-0.2.14...
Installing RDoc documentation for ffi-coremidi-0.1.8...
Installing RDoc documentation for midi-jruby-0.0.12...
Installing RDoc documentation for midi-winmm-0.1.10...
Installing RDoc documentation for unimidi-0.3.3...
Installing RDoc documentation for midi-eye-0.2.2...
Installing RDoc documentation for micromidi-0.0.9...
kerrick@dirk-tooth:~  ruby-1.9.3-p327 
$ irb --simple-prompt
>> require 'midi'
LoadError: Could not open library 'libasound': libasound: cannot open shared object file: No such file or directory.
Could not open library 'libasound.so': libasound.so: cannot open shared object file: No such file or directory
    from /home/kerrick/.rvm/gems/ruby-1.9.3-p327/gems/ffi-1.2.0/lib/ffi/library.rb:121:in `block in ffi_lib'
    from /home/kerrick/.rvm/gems/ruby-1.9.3-p327/gems/ffi-1.2.0/lib/ffi/library.rb:88:in `map'
    from /home/kerrick/.rvm/gems/ruby-1.9.3-p327/gems/ffi-1.2.0/lib/ffi/library.rb:88:in `ffi_lib'
    from /home/kerrick/.rvm/gems/ruby-1.9.3-p327/gems/alsa-rawmidi-0.2.14/lib/alsa-rawmidi/map.rb:11:in `<module:Map>'
    from /home/kerrick/.rvm/gems/ruby-1.9.3-p327/gems/alsa-rawmidi-0.2.14/lib/alsa-rawmidi/map.rb:8:in `<module:AlsaRawMIDI>'
    from /home/kerrick/.rvm/gems/ruby-1.9.3-p327/gems/alsa-rawmidi-0.2.14/lib/alsa-rawmidi/map.rb:3:in `<top (required)>'
    from /home/kerrick/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /home/kerrick/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /home/kerrick/.rvm/gems/ruby-1.9.3-p327/gems/alsa-rawmidi-0.2.14/lib/alsa-rawmidi.rb:14:in `<top (required)>'
    from /home/kerrick/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /home/kerrick/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /home/kerrick/.rvm/gems/ruby-1.9.3-p327/gems/unimidi-0.3.3/lib/unimidi/adapter/alsa-rawmidi.rb:4:in `<top (required)>'
    from /home/kerrick/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /home/kerrick/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /home/kerrick/.rvm/gems/ruby-1.9.3-p327/gems/unimidi-0.3.3/lib/unimidi/platform.rb:22:in `initialize'
    from /home/kerrick/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/singleton.rb:141:in `new'
... 3 levels...
    from /home/kerrick/.rvm/gems/ruby-1.9.3-p327/gems/unimidi-0.3.3/lib/unimidi.rb:20:in `<module:UniMIDI>'
    from /home/kerrick/.rvm/gems/ruby-1.9.3-p327/gems/unimidi-0.3.3/lib/unimidi.rb:19:in `<top (required)>'
    from /home/kerrick/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /home/kerrick/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /home/kerrick/.rvm/gems/ruby-1.9.3-p327/gems/midi-eye-0.2.2/lib/midi-eye.rb:11:in `<top (required)>'
    from /home/kerrick/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /home/kerrick/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /home/kerrick/.rvm/gems/ruby-1.9.3-p327/gems/micromidi-0.0.9/lib/micromidi.rb:13:in `<top (required)>'
    from /home/kerrick/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /home/kerrick/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /home/kerrick/.rvm/gems/ruby-1.9.3-p327/gems/micromidi-0.0.9/lib/midi.rb:15:in `<top (required)>'
    from /home/kerrick/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:60:in `require'
    from /home/kerrick/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:60:in `rescue in require'
    from /home/kerrick/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:35:in `require'
    from (irb):1
    from /home/kerrick/.rvm/rubies/ruby-1.9.3-p327/bin/irb:13:in `<main>'
```

**Comment by DannyBen** [comment]
This should be mentioned in the README.

**Comment by arirusso** [comment]
@DannyBen it's in the README for unimidi but I'll add it here too

**Comment by arirusso** [comment]
added in https://github.com/arirusso/micromidi/commit/1369a099f686f82c389dd96af409c7baca109c42
